# Generated by Django 3.2.6 on 2021-09-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='cover_pics/default_yl9hFW5.jpg', null=True, upload_to='cover_pics'),
        ),
    ]
