# Generated by Django 3.2.6 on 2021-09-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210915_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='account',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_posted',
        ),
    ]
